name: my workflow
on: 
  - workflow_dispatch
  - push
jobs:
    my-first-job:
        runs-on: ubuntu-latest
        steps: 
            - name: Hello Fail
              run: exit 1

    my-second-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print Trigger Event
              run: |
                echo "${{ github.event_name }}"
                echo "Hello From Github Actions Pass 1"

            - name: Hello Pass 2
              run: |
                echo "Hello Github Actions Pass 2"
                echo "Hello From Github Actions Pass 2"
  
